version: "3.7"

services:

  nginx:
    image: nginx:1.19.5
    ports:
      - 80:80
    networks:
      - gis_2021_network
    volumes:
    - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
    - gis_2021_static:/data/static/
    - gis_2021_media:/data/media/

  django:
    image: gis_2021_django:5
    networks:
      - gis_2021_network
    volumes:
    - gis_2021_static:/home/gis_2021/staticfiles/
    - gis_2021_media:/home/gis_2021/media/
    secrets:
      - DJANGO_SECRET_KEY
      - MARIADB_USER
      - MARIADB_PASSWORD

  mariadb:
    image: mariadb:10.5
    networks:
      - gis_2021_network
    volumes:
      - gis_mariadb:/var/lib/mysql
    secrets:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_USER
      - MARIADB_PASSWORD
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/MARIADB_ROOT_PASSWORD
      MARIADB_DATABASE: django
      MARIADB_USER_FILE: /run/secrets/MARIADB_USER
      MARIADB_PASSWORD_FILE: /run/secrets/MARIADB_PASSWORD


networks:
  gis_2021_network:

volumes:
  gis_2021_static:
  gis_2021_media:
  gis_mariadb:

secrets:
  DJANGO_SECRET_KEY:
    external: true
  MARIADB_ROOT_PASSWORD:
    external: true
  MARIADB_USER:
    external: true
  MARIADB_PASSWORD:
    external: true